package com.adibam.samplearch.feed.ui.launch

import android.content.ActivityNotFoundException
import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import com.adibam.samplearch.R
import kotlinx.android.synthetic.main.launch_fragment.*

/*Sample class generated by Android Studio*/
class LaunchFragment : Fragment() {

    companion object {
        fun newInstance() = LaunchFragment()
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return inflater.inflate(R.layout.launch_fragment, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        button_view.setOnClickListener {
            launchFeed()
        }
    }

    /**
     *Feature isolation means we have to go the manual route of handling navigation
     * This could be moved to a separate module altogether
     * But for now its a class as we only have one feature (feed)
     **/

    private fun launchFeed() {
        try {
            requireContext().startActivity(
                Intent(Intent.ACTION_VIEW).setClassName(
                    requireActivity().packageName, "com.adibam.samplearch.feed.ui.FeedActivity"
                )
            )
        } catch (e: ActivityNotFoundException) {
            e.printStackTrace()
        }
    }

}
